package de.alexandermora.erplite.application.command.product;

import jakarta.validation.constraints.*;

import java.math.BigDecimal;

/**
 * Command to create a new Product. Flattens the domain value objects into primitives;
 * carries no productId (generated by the aggregate) and includes the creating user.
 *
 * <p>{@code currency} is checked for shape only ({@code [A-Z]{3}}); ISO-4217 validity is
 * enforced where {@link java.util.Currency} is built (the application service mapping
 * this command to {@code Money}), consistent with the domain.
 */
public record CreateProductCommand(
        @NotBlank(message = "SKU cannot be null or blank")
        @Pattern(regexp = "[A-Z]+-\\d{3}", message = "SKU must match pattern [A-Z]+-NNN")
        String sku,

        @NotBlank(message = "Name cannot be null or blank")
        @Size(min = 3, max = 50, message = "Name must be between 3 and 50 characters")
        String name,

        @Size(max = 1000, message = "Description cannot exceed 1000 characters")
        String description,

        @NotNull(message = "Price cannot be null")
        @DecimalMin(value = "0.01", inclusive = false, message = "Price must be greater than 0")
        BigDecimal price,

        @NotBlank(message = "Currency cannot be null or blank")
        @Pattern(regexp = "[A-Z]{3}", message = "Currency must match pattern [A-Z]{3}")
        String currency,

        @NotNull(message = "Stock cannot be null")
        @Min(value = 0, message = "Stock must be greater than or equal to 0")
        Integer stock,

        @NotBlank(message = "Category ID cannot be null or blank")
        String categoryId,

        byte[] imageData,

        String imageName,

        @NotBlank(message = "CreatedBy cannot be null or blank")
        String createdBy
) {

    /**
     * Custom validation: If imageData is provided, imageName must also be provided
     */
    public CreateProductCommand {
        if (imageData != null && imageData.length > 0 &&
                (imageName == null || imageName.isBlank())) {
            throw new IllegalArgumentException("Image name is required when image data is provided");
        }
    }

    /**
     * Check if this command includes an image upload.
     */
    public boolean hasImage() {
        return imageData != null && imageData.length > 0;
    }

}